## Titan Quest Calculator

You can click any link shown below to get to the mastery overview.

<#list mods as mod>
[${mod.name}](${mod.url})${'\n'} 
</#list>


Post your mod by making a pull request with your database added to the databases folder [Make one now](https://github.com/ByteSquire/TitanQuestCalculator/blob/gh-pages/CONTRIBUTING.md).

### Links
<#list links as linkString, linkURL>
[${linkString}](${linkURL})${'\n'} 
</#list>